### ISSUE TITLE
toy example failing

### ISSUE THREAD

**Issue by nick-youngblut** [zheminzhou/SPARSE#3]
I'm trying to run the toy example as listed in the [docs](http://sparse.readthedocs.io/en/latest/). What's confusing about the documentation in general is that the `setup.py` for this package has an entry point, which creates a `sparse` executable. However, all of the documentation states to use the `SPARSE.py` script in the base of this repo. It is redundant and confusing, and the using `SPARSE.py` script is not appropriate for a python package setup that includes scripts.  

Regardless, I tried the toy example with both scripts and got different errors for both:

## setup

```
conda create -n sparse py=2.7
source activate sparse
pip install meta-sparse
```

## Using the entry point 

```
$ sparse init --dbname toyset
$ sparse index --dbname toyset --seqlist Salmonella_toyset.txt
/ebio/abt3_projects/software/dev/miniconda3_dev/envs/sparse/lib/python2.7/site-packages/SPARSE/modules/A2_db_index.py:125: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  for id, r in enumerate(existing[['assembly_accession', 'file_path', 'url_path']].as_matrix()) \
/ebio/abt3_projects/software/dev/miniconda3_dev/envs/sparse/lib/python2.7/site-packages/SPARSE/modules/A2_db_index.py:128: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  for id, r in enumerate(entries[['assembly_accession', 'file_path', 'url_path']].as_matrix()) \
/ebio/abt3_projects/software/dev/miniconda3_dev/envs/sparse/lib/python2.7/site-packages/SPARSE/modules/A2_db_index.py:138: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  taxids = np.unique(data['taxid'].as_matrix())
/ebio/abt3_projects/software/dev/miniconda3_dev/envs/sparse/lib/python2.7/site-packages/SPARSE/modules/A2_db_index.py:149: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  data[r] = [ (taxa[r].get(tid, ori) if ori == '-' else ori) for tid, ori in data[['taxid', r]].as_matrix() ]
/ebio/abt3_projects/software/dev/miniconda3_dev/envs/sparse/lib/python2.7/site-packages/SPARSE/modules/A2_db_index.py:202: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  for m in entries[ params['taxa_columns'][-1:-4:-1] ].as_matrix()]
/ebio/abt3_projects/software/dev/miniconda3_dev/envs/sparse/lib/python2.7/site-packages/SPARSE/modules/A2_db_index.py:209: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  sha_dict = {c:1 for c in existing['sha256'].as_matrix()}

Program: SPARSE (Strain Prediction and Analysis with Representative SEquences)

Usage:   SPARSE.py <command> [options]

Commands:
  init          Create empty folder structures for a new SPARSE database
  index         Load in a list of assemblies (in RefSeq format) and index them into a SPARSE database
  query         Query metadata info in a SPARSE database
  update        Update metadata info in a SPARSE database
  mapDB         Create bowtie2 or MALT sub-databases for metagenomic reads
  predict       Align reads onto MapDB and do taxonomic predictions, and save all outputs in a specified workspaces
  mash          Compare an assembly with all genomes in a SPARSE database using MASH
  extract       Extract species-specific reads from a SPARSE read-mapping result
  report        Reformat and merge multiple SPARSE workspaces into a flat table. It also predicts human pathogens.

Use SPARSE.py <command> -h to get help for each command.

Traceback (most recent call last):
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/sparse/lib/python2.7/site-packages/SPARSE/SPARSE.py", line 125, in SPARSE
    exec '_{0}(sys.argv[2:])'.format(sys.argv[1])
  File "<string>", line 1, in <module>
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/sparse/lib/python2.7/site-packages/SPARSE/SPARSE.py", line 18, in _index
    return db_index(args.__dict__)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/sparse/lib/python2.7/site-packages/SPARSE/modules/A2_db_index.py", line 228, in db_index
    results = genotype_and_saving(inputs, pool, **params)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/sparse/lib/python2.7/site-packages/SPARSE/modules/A2_db_index.py", line 88, in genotype_and_saving
    return save2mash(inputs, codes, **params)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/sparse/lib/python2.7/site-packages/SPARSE/modules/A2_db_index.py", line 53, in save2mash
    subprocess.Popen('mash paste {0} {1}'.format(db[:-4], ' '.join(infiles)).split(), stderr=subprocess.PIPE, stdout=subprocess.PIPE).communicate()
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/sparse/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/sparse/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

## Using `SPARSE.py`

```
$ python ../SPARSE.py init --dbname toyset
SPARSE is run for the first time. We will compile some C++ codes.
g++ -c -Wall -std=c++0x -fopenmp -I./Ipopt/include solve_model_main.cpp
g++ -c -Wall -std=c++0x -fopenmp -I./Ipopt/include ipopt_run.cpp
g++ -c -Wall -std=c++0x -fopenmp -I./Ipopt/include ipopt_nlp.cpp
g++ -fopenmp -static solve_model_main.o ipopt_run.o ipopt_nlp.o -L./Ipopt/lib64 -L/usr/lib/gcc/x86_64-linux-gnu/5 -L/usr/lib/ -L/lib/ -L/lib64/ -L/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu -lipopt -llapack -ldl -lcoinmumps -lfblas -lpthread -lgfortran -lm -lquadmath -o solve-model
/usr/lib/gcc/x86_64-linux-gnu/5/libgomp.a(target.o): In function `gomp_target_init':
(.text+0xba): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
C++ codes compiled successfully. You will not see these the next time.
done

$ python ../SPARSE.py index --dbname toyset --seqlist Salmonella_toyset.txt

Program: SPARSE (Strain Prediction and Analysis with Representative SEquences)

Usage:   SPARSE.py <command> [options]

Commands:
  init          Create empty folder structures for a new SPARSE database
  index         Load in a list of assemblies (in RefSeq format) and index them into a SPARSE database
  query         Query metadata info in a SPARSE database
  update        Update metadata info in a SPARSE database
  mapDB         Create bowtie2 or MALT sub-databases for metagenomic reads
  predict       Align reads onto MapDB and do taxonomic predictions, and save all outputs in a specified workspaces
  mash          Compare an assembly with all genomes in a SPARSE database using MASH
  extract       Extract species-specific reads from a SPARSE read-mapping result
  report        Reformat and merge multiple SPARSE workspaces into a flat table. It also predicts human pathogens.

Use SPARSE.py <command> -h to get help for each command.

Traceback (most recent call last):
  File "../SPARSE.py", line 125, in SPARSE
    exec '_{0}(sys.argv[2:])'.format(sys.argv[1])
  File "<string>", line 1, in <module>
  File "../SPARSE.py", line 18, in _index
    return db_index(args.__dict__)
  File "/ebio/abt3_projects/software/dev/tmp/sparse/SPARSE/modules/A2_db_index.py", line 185, in db_index
    params = utils.load_paramDict(params)
  File "/ebio/abt3_projects/software/dev/tmp/sparse/SPARSE/modules/utils.py", line 114, in load_paramDict
    config = json.load(open(os.path.join(c2['dbname'], 'dbsetting.cfg')))
IOError: [Errno 2] No such file or directory: 'toyset/dbsetting.cfg'
```

Is the documentation wrong, did I do something wrong, or is this a bug?

**Comment by zheminzhou** [comment]
Thanks for the report. I have fixed the problem for running directly from the SPARSE.py file. Please pull the latest version. It should work. I will have a look at the PIP version now.

**Comment by nick-youngblut** [comment]
OK. Thanks for the quick update! I'll give it a try. 

FYI: I've created a bioconda recipe for `SPARSE` (see https://github.com/bioconda/bioconda-recipes/pull/9011). It's failing on MacOS, and given this issue with the toy example, I'm going to have to close the PR instead of merging it.

**Comment by nick-youngblut** [comment]
The toy example is failing for the [bioconda recipe](https://bioconda.github.io/recipes/meta-sparse/README.html):

```
$ sparse init --dbname toyset
done
$ sparse index --dbname toyset --seqlist Salmonella_toyset.txt
/ebio/abt3_projects/software/dev/miniconda3_dev/envs/sparse/lib/python2.7/site-packages/SPARSE/modules/A2_db_index.py:125: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  for id, r in enumerate(existing[['assembly_accession', 'file_path', 'url_path']].as_matrix()) \
/ebio/abt3_projects/software/dev/miniconda3_dev/envs/sparse/lib/python2.7/site-packages/SPARSE/modules/A2_db_index.py:128: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  for id, r in enumerate(entries[['assembly_accession', 'file_path', 'url_path']].as_matrix()) \
/ebio/abt3_projects/software/dev/miniconda3_dev/envs/sparse/lib/python2.7/site-packages/SPARSE/modules/A2_db_index.py:138: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  taxids = np.unique(data['taxid'].as_matrix())
/ebio/abt3_projects/software/dev/miniconda3_dev/envs/sparse/lib/python2.7/site-packages/SPARSE/modules/A2_db_index.py:149: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  data[r] = [ (taxa[r].get(tid, ori) if ori == '-' else ori) for tid, ori in data[['taxid', r]].as_matrix() ]
/ebio/abt3_projects/software/dev/miniconda3_dev/envs/sparse/lib/python2.7/site-packages/SPARSE/modules/A2_db_index.py:202: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  for m in entries[ params['taxa_columns'][-1:-4:-1] ].as_matrix()]
/ebio/abt3_projects/software/dev/miniconda3_dev/envs/sparse/lib/python2.7/site-packages/SPARSE/modules/A2_db_index.py:209: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  sha_dict = {c:1 for c in existing['sha256'].as_matrix()}

Program: SPARSE (Strain Prediction and Analysis with Representative SEquences)

Usage:   SPARSE.py <command> [options]

Commands:
  init          Create empty folder structures for a new SPARSE database
  index         Load in a list of assemblies (in RefSeq format) and index them into a SPARSE database
  query         Query metadata info in a SPARSE database
  update        Update metadata info in a SPARSE database
  mapDB         Create bowtie2 or MALT sub-databases for metagenomic reads
  predict       Align reads onto MapDB and do taxonomic predictions, and save all outputs in a specified workspaces
  mash          Compare an assembly with all genomes in a SPARSE database using MASH
  extract       Extract species-specific reads from a SPARSE read-mapping result
  report        Reformat and merge multiple SPARSE workspaces into a flat table. It also predicts human pathogens.

Use SPARSE.py <command> -h to get help for each command.

Traceback (most recent call last):
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/sparse/lib/python2.7/site-packages/SPARSE/SPARSE.py", line 125, in SPARSE
    exec '_{0}(sys.argv[2:])'.format(sys.argv[1])
  File "<string>", line 1, in <module>
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/sparse/lib/python2.7/site-packages/SPARSE/SPARSE.py", line 18, in _index
    return db_index(args.__dict__)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/sparse/lib/python2.7/site-packages/SPARSE/modules/A2_db_index.py", line 228, in db_index
    results = genotype_and_saving(inputs, pool, **params)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/sparse/lib/python2.7/site-packages/SPARSE/modules/A2_db_index.py", line 88, in genotype_and_saving
    return save2mash(inputs, codes, **params)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/sparse/lib/python2.7/site-packages/SPARSE/modules/A2_db_index.py", line 53, in save2mash
    subprocess.Popen('mash paste {0} {1}'.format(db[:-4], ' '.join(infiles)).split(), stderr=subprocess.PIPE, stdout=subprocess.PIPE).communicate()
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/sparse/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/sparse/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Any idea on what's causing it?

My environment:

```
$ conda list
# packages in environment at /ebio/abt3_projects/software/dev/miniconda3_dev/envs/sparse:
#
# Name                    Version                   Build  Channel
ca-certificates           2018.4.16                     0    conda-forge
certifi                   2018.4.16                py27_0    conda-forge
cython                    0.28.3                   py27_0    conda-forge
Cython                    0.28.2                    <pip>
intel-openmp              2018.0.3                      0
libgcc-ng                 7.2.0                hdf63c60_3
libgfortran-ng            7.2.0                hdf63c60_3
libopenblas               0.2.20               h9ac9557_7
libstdcxx-ng              7.2.0                hdf63c60_3
meta-sparse               0.1.2                     <pip>
meta-sparse               0.1.2                    py27_0    bioconda
mkl                       2018.0.3                      1
mkl_fft                   1.0.2                    py27_0    conda-forge
mkl_random                1.0.1                    py27_0    conda-forge
msgpack                   0.5.6                     <pip>
msgpack-python            0.5.6            py27h2d50403_2    conda-forge
ncurses                   5.9                          10    conda-forge
numpy                     1.14.3                    <pip>
numpy                     1.14.3           py27hcd700cb_2
numpy-base                1.14.3           py27h0ea5e3f_1
openssl                   1.0.2o                        0    conda-forge
pandas                    0.23.0                    <pip>
pandas                    0.23.0                   py27_1    conda-forge
pip                       9.0.3                    py27_0    conda-forge
pycapnp                   0.6.3                     <pip>
pycapnp                   0.6.3                    py27_0    conda-forge
python                    2.7.15                        0    conda-forge
python-dateutil           2.7.3                      py_0    conda-forge
python-dateutil           2.7.3                     <pip>
pytz                      2018.4                     py_0    conda-forge
readline                  7.0                           0    conda-forge
scipy                     1.1.0            py27hfc37229_0
scipy                     1.1.0                     <pip>
setuptools                39.2.0                   py27_0    conda-forge
six                       1.11.0                    <pip>
six                       1.11.0                   py27_1    conda-forge
sqlite                    3.20.1                        2    conda-forge
tk                        8.6.7                         0    conda-forge
wheel                     0.31.0                   py27_0    conda-forge
zlib                      1.2.11                        0    conda-forge
```
